export const TurboEvents = {
  Click: 'turbo:click',
  BeforeVisit: 'turbo:before-visit',
  Visit: 'turbo:visit',
  BeforeCache: 'before-cache',
  BeforeRender: 'turbo:before-render',
  Render: 'turbo:render',
  Load: 'turbo:load',
  Morph: 'morph',
  BeforeMorphElement: 'turbo:before-morph-element',
  BeforeMorphAttribute: 'turbo:before-morph-attribute',
  MorphElement: 'turbo:morph-element',
  SubmitStart: 'turbo:submit-start',
  SubmitEnd: 'turbo:submit-end',
  BeforeFrameRender: 'turbo:before-frame-render',
  FrameRender: 'turbo:frame-render',
  FrameLoad: 'turbo:frame-load',
  FrameMissing: 'turbo:frame-missing',
  BeforeStremRender: 'turbo:before-stream-render',
  BeforeFetchRequest: 'turbo:before-fetch-request',
  BeforeFetchResponse: 'turbo:before-fetch-response',
  BeforePrefetch: 'turbo:before-prefetch',
  FetchRequestError: 'turbo:fetch-request-error',
}
